#!/usr/bin/env python3
import json

# Read Spanish file
with open('public/assets/i18n/es.json', 'r', encoding='utf-8') as f:
    es_data = json.load(f)

# Complete Spanish PRIVACY translations - ALL 243 keys
es_data["PRIVACY"] = {
    "TITLE": "Política de Privacidad",
    "LAST_UPDATED": "Última Actualización",
    "INTRO_TITLE": "Introducción",
    "INTRO_TEXT": "Music Rights Platform (\"nosotros\", \"nuestro\" o \"Compañía\") opera el sitio web y la aplicación Music Rights Platform. Esta Política de Privacidad explica cómo recopilamos, usamos, divulgamos y protegemos su información cuando usa nuestro Servicio.",
    "PASSION_PROJECT": "Este es un Proyecto Personal—No un Servicio Comercial",
    "PASSION_1": "Esta plataforma es un proyecto personal no comercial creado por un individuo.",
    "PASSION_2": "No es una empresa registrada, LLC o entidad comercial legal.",
    "PASSION_3": "No hay equipo de soporte dedicado, línea de atención al cliente o Acuerdo de Nivel de Servicio (SLA).",
    "PASSION_4": "Las funciones, el tiempo de actividad y la funcionalidad se proporcionan solo con el \"mejor esfuerzo\".",
    "PASSION_5": "No hacemos garantías sobre la fiabilidad, disponibilidad, precisión o idoneidad para ningún propósito particular.",
    "NO_LIABILITY": "Sin Responsabilidad por Daños o Pérdidas",
    "NO_LIABILITY_TEXT": "Al usar esta plataforma, usted reconoce y acepta que NO asumimos ninguna responsabilidad por pérdidas, daños, pérdida de datos u otras consecuencias derivadas de su uso de este Servicio. Uso completamente bajo su propio riesgo.",
    "ACKNOWLEDGMENT": "Reconocimiento de Términos",
    "GDPR_COMPLIANCE": "Aunque este es un proyecto personal, cumplimos con el <strong>Reglamento General de Protección de Datos (GDPR)</strong> y las leyes europeas de protección de datos aplicables.",
    "INVITE_TITLE": "Acceso Solo por Invitación y Derecho a Rechazar el Servicio",
    "NOT_PUBLIC": "No es un Servicio Público",
    "INVITE_ACCESS": "Esta plataforma es solo por invitación y actualmente está en beta cerrada. El acceso se otorga a nuestra entera discreción.",
    "INVITE_1": "El registro puede requerir un código de invitación o aprobación manual.",
    "INVITE_2": "No garantizamos el acceso a todos los que lo soliciten.",
    "INVITE_3": "Su acceso puede ser revocado en cualquier momento sin previo aviso.",
    "WE_RESERVE": "Nos Reservamos el Derecho de Rechazar el Servicio",
    "RESERVE_1": "Podemos denegar, suspender o terminar el acceso para cualquier usuario, en cualquier momento, por cualquier motivo.",
    "RESERVE_2": "No estamos obligados a proporcionar explicaciones para la denegación o terminación.",
    "RESERVE_3": "No somos responsables de ninguna consecuencia de la suspensión o terminación de la cuenta.",
    "YOU_ACKNOWLEDGE": "Usted Reconoce",
    "ACKNOWLEDGE_1": "Este servicio es experimental, sujeto a cambios y puede descontinuarse sin previo aviso.",
    "ACKNOWLEDGE_2": "No hay derecho al acceso continuo o tiempo de actividad.",
    "ACKNOWLEDGE_3": "No hacemos promesas sobre la disponibilidad de funciones o persistencia de datos.",
    "ACKNOWLEDGE_4": "El uso de esta plataforma es un privilegio, no un derecho.",
    "CONTROLLER_TITLE": "Controlador de Datos e Información de Contacto",
    "CONTROLLER_TEXT": "El controlador de datos responsable de sus datos personales es el operador de la plataforma.",
    "CONTACT_TITLE": "Contacto",
    "CONTACT_TEXT": "Para consultas de privacidad, use la función de soporte dentro de la aplicación (si está disponible).",
    "GDPR_REQUESTS": "Solicitudes de Interesados GDPR",
    "GDPR_REQUESTS_TEXT": "Para solicitudes GDPR, contáctenos a través de los métodos anteriores. Respondemos en 30 días.",
    "DPA_TITLE": "Autoridad de Protección de Datos",
    "DPA_TEXT": "Puede contactar a su autoridad local de protección de datos con inquietudes.",
    "COLLECTION_TITLE": "Qué Información Recopilamos",
    "VOLUNTARY_TITLE": "Información que Usted Proporciona (Voluntaria)",
    "VOLUNTARY_TEXT": "Recopilamos información que usted proporciona voluntariamente:",
    "ACCOUNT_INFO": "Información de Cuenta",
    "ACCOUNT_INFO_TEXT": "Correo electrónico, contraseña (hasheada), nombre para mostrar, foto de perfil opcional.",
    "PROFILE_INFO": "Datos de Perfil",
    "PROFILE_INFO_TEXT": "Nombre, seudónimo/apodo, IPI, ISNI, PRO/CMO, detalles de contacto.",
    "WORK_INFO": "Obras Musicales y Metadatos",
    "WORK_INFO_TEXT": "Títulos de canciones, códigos ISWC, ISRC, fechas de lanzamiento, colaboradores, divisiones.",
    "RIGHTS_INFO": "Información de Titulares de Derechos",
    "RIGHTS_INFO_TEXT": "Compositor, letrista, editor, detalles de intérprete, roles, divulgaciones de IA.",
    "SPLIT_INFO": "Protocolo y Acuerdos de División",
    "SPLIT_INFO_TEXT": "Porcentajes de división, firmas, códigos QR, documentos PDF de protocolo.",
    "IMPORTANT": "Importante",
    "USER_RESPONSIBILITY": "Usted es el único responsable de la precisión de cualquier información que cargue.",
    "NO_VERIFY": "No verificamos la precisión de los datos proporcionados por el usuario.",
    "AUTO_TITLE": "Información Recopilada Automáticamente",
    "AUTO_TEXT": "Recopilamos automáticamente información técnica:",
    "AUTO_1": "Información del dispositivo (tipo, SO, navegador)",
    "AUTO_2": "Dirección IP y ubicación aproximada",
    "AUTO_3": "Marcas de tiempo y duración de la sesión",
    "AUTO_4": "Páginas visitadas y funciones utilizadas",
    "AUTO_5": "Registros de errores y métricas de rendimiento",
    "AUTO_PURPOSE": "Estos datos se utilizan para funcionalidad, seguridad, depuración y mejoras.",
    "MUSIC_TITLE": "Datos Específicos de la Industria Musical",
    "MUSIC_TEXT": "Recopilamos datos de gestión de derechos musicales:",
    "NICKNAME_LABEL": "Apodos/Seudónimos",
    "NICKNAME_TEXT": "Nombres artísticos o alias que utiliza profesionalmente.",
    "IPI_LABEL": "Número IPI",
    "IPI_TEXT": "Identificador único asignado por organizaciones de derechos de interpretación.",
    "ISNI_LABEL": "ISNI",
    "ISNI_TEXT": "Identificador Internacional Estándar de Nombre para colaboradores.",
    "CMO_LABEL": "Membresía CMO/PRO",
    "CMO_TEXT": "Su afiliación con organizaciones como GEMA, ASCAP, PRS.",
    "AI_LABEL": "Divulgación de IA",
    "AI_TEXT": "Si se utilizó IA en la creación de la obra.",
    "NICKNAME_SYSTEM": "Sistema de Apodos/ID de Perfil",
    "NICKNAME_1": "Generamos un profile_id único para cada usuario.",
    "NICKNAME_2": "Puede crear un apodo que se vincule a su profile_id.",
    "NICKNAME_3": "Los apodos son públicamente visibles si su perfil es público.",
    "AI_DISCLOSURES": "Divulgaciones de IA",
    "AI_DISC_1": "Puede indicar si una obra utilizó herramientas de IA.",
    "AI_DISC_2": "Esta información aparece en los metadatos públicos de la obra y protocolos.",
    "AI_DISC_3": "La divulgación precisa es su responsabilidad.",
    "DISCLAIMER": "Descargo de Responsabilidad",
    "DISCLAIMER_TEXT": "NO somos un reemplazo de asesoramiento legal o editores musicales profesionales. Esta es una herramienta para registro personal.",
    "LEGAL_BASIS_TITLE": "Base Legal para el Procesamiento (GDPR)",
    "LEGAL_BASIS_TEXT": "Procesamos sus datos basándonos en:",
    "BASIS_CONTRACT": "Necesidad Contractual",
    "BASIS_CONTRACT_TEXT": "Para proporcionar nuestro Servicio (creación de cuenta, almacenamiento de obras, protocolos).",
    "BASIS_INTEREST": "Intereses Legítimos",
    "BASIS_INTEREST_TEXT": "Para mejorar la plataforma, garantizar la seguridad, prevenir fraudes.",
    "BASIS_LEGAL": "Obligaciones Legales",
    "BASIS_LEGAL_TEXT": "Para cumplir con las leyes aplicables.",
    "BASIS_CONSENT": "Consentimiento",
    "BASIS_CONSENT_TEXT": "Cuando se solicita explícitamente (marketing, funciones opcionales).",
    "USAGE_TITLE": "Cómo Usamos Su Información",
    "USAGE_TEXT": "Usamos sus datos personales para:",
    "USAGE_1": "Crear y gestionar su cuenta.",
    "USAGE_2": "Habilitar la colaboración y gestión de derechos.",
    "USAGE_3": "Generar documentos de protocolo y códigos QR.",
    "USAGE_4": "Comunicarnos con usted (notificaciones, alertas).",
    "USAGE_5": "Mejorar la funcionalidad de la plataforma.",
    "USAGE_6": "Garantizar la seguridad y prevenir abusos.",
    "USAGE_7": "Cumplir con obligaciones legales.",
    "NO_ADS": "No usamos sus datos para publicidad ni los vendemos a terceros.",
    "NO_GUARANTEES": "Sin Garantías",
    "NO_GUARANTEES_TEXT": "No hacemos garantías sobre la precisión de los datos o el tiempo de actividad de la plataforma.",
    "SHARING_TITLE": "Cuándo y Cómo Compartimos Su Información",
    "PROVIDERS_TITLE": "Proveedores de Servicios e Infraestructura",
    "PROVIDERS_TEXT": "Usamos servicios de terceros:",
    "SUPABASE_DESC": "Backend para autenticación, base de datos, almacenamiento.",
    "SUPABASE_1": "Ubicación de Datos: región UE (compatible con GDPR)",
    "SUPABASE_2": "Datos Procesados: correo electrónico, contraseñas, perfiles, obras, protocolos",
    "SUPABASE_3": "Seguridad: cifrado TLS/SSL, controles de acceso",
    "SUPABASE_4": "Política de Privacidad",
    "SUPABASE_5": "Usa subprocesadores (AWS) con DPA conformes a GDPR.",
    "AUTH_STORAGE": "Autenticación y Almacenamiento de Sesión",
    "AUTH_STORAGE_TEXT": "Supabase usa tokens almacenados en localStorage del navegador para sesiones.",
    "NETLIFY_DESC": "Alojamiento frontend y entrega de contenido.",
    "NETLIFY_1": "Datos Procesados: direcciones IP, datos del navegador",
    "NETLIFY_2": "Seguridad: cifrado HTTPS, protección DDoS",
    "NETLIFY_3": "Política de Privacidad",
    "PROVIDERS_DISCLAIMER": "No podemos garantizar la seguridad o el tiempo de actividad de proveedores externos.",
    "COLLAB_TITLE": "Colaboración y Espacios de Trabajo Compartidos",
    "COLLAB_TEXT": "Al colaborar, sus datos compartidos son visibles para los colaboradores.",
    "COLLAB_1": "Usted controla qué información comparte.",
    "COLLAB_2": "No somos responsables de cómo otros usan la información compartida.",
    "COLLAB_3": "Tenga cuidado con el acceso al espacio de trabajo.",
    "LEGAL_REQ_TITLE": "Requisitos Legales",
    "LEGAL_REQ_TEXT": "Podemos divulgar información si la ley lo requiere:",
    "LEGAL_1": "Cumplir con citaciones u órdenes judiciales.",
    "LEGAL_2": "Hacer cumplir nuestros Términos de Servicio.",
    "LEGAL_3": "Proteger derechos, propiedad o seguridad.",
    "LEGAL_LIMITATION": "Como proyecto personal, nuestra capacidad para impugnar solicitudes legales es limitada.",
    "TRANSFER_TITLE": "Transferencias Internacionales de Datos",
    "TRANSFER_TEXT": "Los datos se almacenan principalmente en la UE. Algunos subprocesadores operan globalmente con salvaguardias adecuadas (Cláusulas Contractuales Estándar, DPA conformes a GDPR).",
    "COOKIES_TITLE": "Cookies, Almacenamiento Local y Seguimiento",
    "COOKIES_SUB": "¿Qué son las Cookies?",
    "COOKIES_TEXT": "NO usamos cookies de seguimiento tradicionales o servicios de análisis.",
    "COOKIES_AUTH": "Supabase usa tokens seguros en localStorage para autenticación.",
    "STORAGE_TITLE": "Qué Almacenamos Localmente",
    "STORAGE_TEXT": "Usamos localStorage del navegador para:",
    "STORAGE_1": "Tokens de autenticación",
    "STORAGE_2": "Preferencias del usuario (espacio de trabajo, tema)",
    "STORAGE_LOCAL": "Estos datos permanecen en su dispositivo.",
    "NO_TRACK_TITLE": "Sin Seguimiento de Terceros",
    "NO_TRACK_TEXT": "No usamos Google Analytics, Facebook Pixel o herramientas similares.",
    "FUTURE_CHANGE": "Si agregamos análisis, actualizaremos esta política y obtendremos consentimiento.",
    "QR_TITLE": "Escaneo de Código QR",
    "QR_TEXT": "Nuestra funcionalidad de escaneo de código QR:",
    "QR_1_LABEL": "Acceso a la Cámara del Navegador",
    "QR_1": "Solicitamos acceso temporal a la cámara a través de permisos del navegador.",
    "QR_2_LABEL": "Procesamiento de Datos",
    "QR_2": "El flujo de la cámara se procesa localmente en su navegador. No se carga ningún video.",
    "QR_3_LABEL": "Datos del Código QR",
    "QR_3": "Si un código QR contiene un ID de protocolo, consultamos nuestra base de datos.",
    "QR_4_LABEL": "Privacidad",
    "QR_4": "No almacenamos imágenes de cámara ni videos.",
    "RETENTION_TITLE": "Retención y Eliminación de Datos",
    "RETENTION_TEXT": "Retenemos datos solo el tiempo necesario.",
    "DELETION_TITLE": "Eliminación de Cuenta",
    "DELETION_TEXT": "Puede solicitar la eliminación de la cuenta en cualquier momento.",
    "PERIODS_TITLE": "Períodos de Retención",
    "PERIOD_1_LABEL": "Cuentas Activas",
    "PERIOD_1": "Los datos se retienen mientras la cuenta esté activa.",
    "PERIOD_2_LABEL": "Cuentas Eliminadas",
    "PERIOD_2": "Los datos personales se eliminan en 30 días.",
    "PERIOD_3_LABEL": "Datos Compartidos",
    "PERIOD_3": "Los metadatos de obras compartidas pueden permanecer visibles para los colaboradores.",
    "PERIOD_4_LABEL": "Copias de Seguridad",
    "PERIOD_4": "Las copias de seguridad persisten hasta 90 días.",
    "PERIOD_5_LABEL": "Retenciones Legales",
    "PERIOD_5": "Los datos sujetos a investigación legal se retienen hasta que se resuelvan.",
    "PERIOD_6_LABEL": "Registros",
    "PERIOD_6": "Los registros del servidor se retienen hasta 12 meses.",
    "DISCONTINUE_TITLE": "Descontinuación del Servicio",
    "DISCONTINUE_TEXT": "Si descontinuamos, haremos esfuerzos razonables para notificar a los usuarios y proporcionar exportación de datos.",
    "RIGHTS_TITLE": "Sus Derechos Bajo GDPR",
    "RIGHTS_TEXT": "Tiene los siguientes derechos:",
    "RIGHT_1": "Derecho de Acceso",
    "RIGHT_1_TEXT": "Solicitar una copia de sus datos personales.",
    "RIGHT_2": "Derecho de Rectificación",
    "RIGHT_2_TEXT": "Corregir datos inexactos.",
    "RIGHT_3": "Derecho de Supresión",
    "RIGHT_3_TEXT": "Solicitar la eliminación de sus datos.",
    "RIGHT_4": "Derecho a Restringir el Procesamiento",
    "RIGHT_4_TEXT": "Limitar cómo usamos sus datos.",
    "RIGHT_5": "Derecho a la Portabilidad de Datos",
    "RIGHT_5_TEXT": "Recibir sus datos en formato legible por máquina.",
    "RIGHT_6": "Derecho a Oponerse",
    "RIGHT_6_TEXT": "Oponerse al procesamiento basado en intereses legítimos.",
    "RIGHT_7": "Derecho a Retirar el Consentimiento",
    "RIGHT_7_TEXT": "Retirar el consentimiento en cualquier momento.",
    "EXERCISE_TITLE": "Cómo Ejercer Sus Derechos",
    "EXERCISE_LABEL": "Para ejercer derechos:",
    "EXERCISE_1": "Contáctenos usando la información en la Sección 3.",
    "EXERCISE_2": "Respondemos en 30 días.",
    "EXERCISE_3": "Podemos verificar su identidad.",
    "LIMITATIONS": "Limitaciones",
    "LIMITATIONS_TEXT": "Ciertos derechos pueden estar limitados por obligaciones legales.",
    "COMPLAINT": "Derecho a Presentar una Queja",
    "COMPLAINT_TEXT": "Presentar quejas ante su autoridad local de protección de datos.",
    "SECURITY_TITLE": "Seguridad de Datos",
    "SECURITY_TEXT": "Tomamos medidas de seguridad razonables:",
    "SECURITY_1": "Cifrado: HTTPS/TLS para transmisión de datos.",
    "SECURITY_2": "Contraseñas Hasheadas: Usando bcrypt.",
    "SECURITY_3": "Controles de Acceso: Acceso backend limitado.",
    "SECURITY_4": "Actualizaciones Regulares: Se aplican parches de seguridad.",
    "HOWEVER": "Sin Embargo",
    "SECURITY_LIMITS": "Ningún sistema es 100% seguro. Carecemos de medidas de seguridad de nivel empresarial. Use bajo su propio riesgo.",
    "BEST_PRACTICES": "Su Responsabilidad",
    "PRACTICE_1": "Use una contraseña fuerte y única.",
    "PRACTICE_2": "No comparta credenciales de inicio de sesión.",
    "PRACTICE_3": "Cierre sesión en dispositivos compartidos.",
    "PRACTICE_4": "Informe actividad sospechosa de inmediato.",
    "BREACH_TITLE": "Notificación de Violación de Datos",
    "BREACH_TEXT": "Le notificaremos a usted y a las autoridades dentro de las 72 horas de una violación.",
    "CHILDREN_TITLE": "Privacidad de Menores",
    "CHILDREN_TEXT": "Este Servicio no es para personas menores de 16 años. No recopilamos datos de menores a sabiendas.",
    "WARRANTY_TITLE": "Sin Garantías o Aseguraciones",
    "WARRANTY_TEXT": "ESTE SERVICIO SE PROPORCIONA \"TAL CUAL\" SIN GARANTÍAS.",
    "WARRANTY_LIST": "No hacemos garantías sobre el tiempo de actividad, precisión, copia de seguridad de datos o validez legal de documentos.",
    "USE_RISK": "Usa esta plataforma completamente bajo su propio riesgo.",
    "LIABILITY_TITLE": "Limitación de Responsabilidad",
    "LIABILITY_TEXT": "NO SEREMOS RESPONSABLES DE NINGÚN:",
    "LIABILITY_LIST": "Daños directos, indirectos, consecuentes; pérdida de datos, ingresos o ganancias; errores o infracciones; tiempo de inactividad o interrupciones; acciones de terceros.",
    "LIABILITY_ACK": "Este es un proyecto gratuito y experimental. No asumimos responsabilidad legal. Busque alternativas comerciales si necesita confiabilidad garantizada.",
    "CHANGES_TITLE": "Cambios a Esta Política de Privacidad",
    "CHANGES_TEXT": "Podemos actualizar esta política. Los cambios se publican con la fecha actualizada de \"Última Actualización\".",
    "CONTINUED_USE": "El uso continuado después de los cambios constituye aceptación.",
    "ACCEPTANCE_TITLE": "Aceptación de Esta Política",
    "BY_USING": "Al usar Music Rights Platform, usted reconoce:",
    "ACCEPT_1": "Este es un proyecto personal, no un servicio comercial.",
    "ACCEPT_2": "Sin garantías de tiempo de actividad, precisión o confiabilidad.",
    "ACCEPT_3": "No asumimos responsabilidad por daños o pérdidas.",
    "ACCEPT_4": "Podemos denegar o terminar el acceso en cualquier momento.",
    "ACCEPT_5": "Usted entiende sus derechos GDPR.",
    "ACCEPT_6": "Acepta los riesgos de usar una plataforma experimental.",
    "NO_AGREE": "Si no está de acuerdo, no use este Servicio.",
    "CONTACT_SECTION": "Información de Contacto y Quejas",
    "NO_SUPPORT": "Sin equipo de soporte dedicado. Las respuestas pueden retrasarse.",
    "USE_INAPP": "Use la función de soporte dentro de la aplicación o información de contacto en la Sección 3.",
    "SERIOUS_CONCERNS": "Para Preocupaciones Serias de Privacidad",
    "DPA_CONTACT": "Contacte a su Autoridad Local de Protección de Datos:",
    "FOOTER": "Este es un proyecto personal. Use bajo su propio riesgo."
}

# Write back to file with proper formatting
with open('public/assets/i18n/es.json', 'w', encoding='utf-8') as f:
    json.dump(es_data, f, ensure_ascii=False, indent=2)

print("✅ Complete Spanish PRIVACY translations fixed!")
print(f"Total PRIVACY keys: {len(es_data['PRIVACY'])}")
